🐞 Let's Encrypt's DNS propagation is a string
...and not an integer, which causes failures.

fixes
<https://ci.cli.fun/teams/main/pipelines/bosh-lites/jobs/create-bosh-lite/builds/710>
```
Error: acme_certificate.certificate: DNS challenge config map values must be strings only
```

Co-authored-by: Mona Mohebbi <mmohebbi@pivotal.io>
Co-authored-by: Brian Cunnie <bcunnie@pivotal.io>
Co-authored-by: Joseph Palermo <jpalermo@pivotal.io>
Co-authored-by: Brendan Smith <brsmith@pivotal.io>