Revert "🐞 Remove terraform's deprecation warnings"
This reverts commit d890afd80c64c6aea24128250f70b43f09ac62ac.

fixes:
```
Error: Error parsing /tmp/build/put/capi-ci/terraform/bosh-lite/bosh-lite.tf: At 28:17: Unknown token: 28:17 IDENT var.json_key
```